// // <copyright file="SettingsData.cs" company="PublicDomain.com">
// //     CC0 1.0 Universal (CC0 1.0) - Public Domain Dedication
// //     https://creativecommons.org/publicdomain/zero/1.0/legalcode
// // </copyright>
// // <auto-generated />

namespace PublicDomain
{
    // Directives
    using System.Collections.Generic;

    /// <summary>
    /// Urlister settings.
    /// </summary>
    public class SettingsData
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="T:PublicDomain.SettingsData"/> class.
        /// </summary>
        public SettingsData()
        {
            // Parameterless constructor
        }

        /// <summary>
        /// Gets or sets a value indicating whether this <see cref="T:PublicDomain.SettingsData"/> save on exit.
        /// </summary>
        /// <value><c>true</c> if save on exit; otherwise, <c>false</c>.</value>
        public bool SaveOnExit { get; set; } = true;

        /// <summary>
        /// The pad text list.
        /// </summary>
        public List<string> padTextList = new List<string>();
    }
}